# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('last_grid_id', models.IntegerField(default=-1)),
                ('supermarket', models.BooleanField(default=False)),
                ('gasstation', models.BooleanField(default=False)),
                ('drugstore', models.BooleanField(default=False)),
                ('atm', models.BooleanField(default=False)),
                ('postoffice', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
            ],
        ),
    ]
