# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appserver', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
