# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appserver', '0003_location_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='drugstore',
            new_name='pharmacy',
        ),
    ]
