# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appserver', '0004_auto_20180315_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gym',
            new_name='shoppingmall',
        ),
    ]
