# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appserver', '0005_auto_20180315_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pharmacy',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
