# Generated by Django 2.0.3 on 2018-03-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appserver', '0006_auto_20180316_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(null=True),
        ),
    ]
